//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.02 at 04:23:52 PM BST 
//

package org.orcid.jaxb.model.message;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
import java.io.Serializable;

/**
 * Java class for anonymous complex type.
 * 
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.orcid.org/ns/orcid}contributor-sequence"/&gt;
 *         &lt;element ref="{http://www.orcid.org/ns/orcid}contributor-role"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType( propOrder = { "contributorSequence", "contributorRole" })
@XmlRootElement(name = "contributor-attributes")
public class ContributorAttributes implements Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    @XmlElement(name = "contributor-sequence", required = true)
    protected SequenceType contributorSequence;
    @XmlElement(name = "contributor-role", required = true)
    protected ContributorRole contributorRole;

    /**
     * Gets the value of the contributorSequence property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public SequenceType getContributorSequence() {
        return contributorSequence;
    }

    /**
     * Sets the value of the contributorSequence property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContributorSequence(SequenceType value) {
        this.contributorSequence = value;
    }

    /**
     * Gets the value of the contributorRole property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public ContributorRole getContributorRole() {
        return contributorRole;
    }

    /**
     * Sets the value of the contributorRole property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContributorRole(ContributorRole value) {
        this.contributorRole = value;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (!(o instanceof ContributorAttributes)) {
            return false;
        }

        ContributorAttributes that = (ContributorAttributes) o;

        if (contributorRole != that.contributorRole) {
            return false;
        }
        if (contributorSequence != that.contributorSequence) {
            return false;
        }

        return true;
    }

    @Override
    public int hashCode() {
        int result = contributorSequence != null ? contributorSequence.hashCode() : 0;
        result = 31 * result + (contributorRole != null ? contributorRole.hashCode() : 0);
        return result;
    }
}
