//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.02 at 11:50:02 AM BST 
//

package org.orcid.jaxb.model.message;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
import java.io.Serializable;

/**
 * Java class for anonymous complex type.
 * 
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.orcid.org/ns/orcid}orcid"/&gt;
 *         &lt;element ref="{http://www.orcid.org/ns/orcid}credit-name" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(propOrder = { "orcid", "orcidIdentifier", "lastModifiedDate", "creditName" })
@XmlRootElement(name = "delegate-summary")
public class DelegateSummary implements Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    @XmlElement
    protected Orcid orcid;
    @XmlElement(name = "orcid-identifier")
    protected OrcidIdentifier orcidIdentifier;
    @XmlElement(name = "last-modified-date")
    protected LastModifiedDate lastModifiedDate;
    @XmlElement(name = "credit-name")
    protected CreditName creditName;

    public DelegateSummary() {
        super();
    }

    @Deprecated
    public DelegateSummary(Orcid orcid) {
        this.orcid = orcid;
        this.orcidIdentifier = new OrcidIdentifier(orcid.getValue());
    }

    public DelegateSummary(OrcidIdentifier orcidIdentifier) {
        this.orcidIdentifier = orcidIdentifier;
    }

    /**
     * Gets the value of the orcid property.
     * 
     * @return possible object is {@link Orcid }
     * 
     */
    @Deprecated
    public Orcid getOrcid() {
        return orcid;
    }

    /**
     * Sets the value of the orcid property.
     * 
     * @param value
     *            allowed object is {@link Orcid }
     * 
     */
    @Deprecated
    public void setOrcid(Orcid value) {
        this.orcid = value;
    }

    public OrcidIdentifier getOrcidIdentifier() {
        return orcidIdentifier;
    }

    public void setOrcidIdentifier(OrcidIdentifier orcidIdentifier) {
        this.orcidIdentifier = orcidIdentifier;
    }

    public LastModifiedDate getLastModifiedDate() {
        return lastModifiedDate;
    }

    public void setLastModifiedDate(LastModifiedDate lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
    }

    /**
     * Gets the value of the creditName property.
     * 
     * @return possible object is {@link CreditName }
     * 
     */
    public CreditName getCreditName() {
        return creditName;
    }

    /**
     * Sets the value of the creditName property.
     * 
     * @param value
     *            allowed object is {@link CreditName }
     * 
     */
    public void setCreditName(CreditName value) {
        this.creditName = value;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (!(o instanceof DelegateSummary)) {
            return false;
        }

        DelegateSummary that = (DelegateSummary) o;

        if (creditName != null ? !creditName.equals(that.creditName) : that.creditName != null) {
            return false;
        }
        if (orcid != null ? !orcid.equals(that.orcid) : that.orcid != null) {
            return false;
        }

        return true;
    }

    @Override
    public int hashCode() {
        int result = orcid != null ? orcid.hashCode() : 0;
        result = 31 * result + (creditName != null ? creditName.hashCode() : 0);
        return result;
    }
}
