//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.09 at 01:52:56 PM BST 
//

package org.orcid.jaxb.model.message;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
import java.io.Serializable;

/**
 * Java class for anonymous complex type.
 * 
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.orcid.org/ns/orcid}agency-orcid"/&gt;
 *         &lt;element ref="{http://www.orcid.org/ns/orcid}agency-name"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType( propOrder = { "agencyOrcid", "agencyName" })
@XmlRootElement(name = "funding-agency")
public class FundingAgency implements Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    @XmlElement(name = "agency-orcid")
    protected AgencyOrcid agencyOrcid;
    @XmlElement(name = "agency-name")
    protected AgencyName agencyName;

    /**
     * Gets the value of the AgencyOrcid property.
     * 
     * @return
     *     possible object is
     *     {@link AgencyOrcid }
     *     
     */
    public AgencyOrcid getAgencyOrcid() {
        return agencyOrcid;
    }

    /**
     * Sets the value of the agencyOrcid property.
     * 
     * @param value
     *     allowed object is
     *     {@link AgencyOrcid }
     *     
     */
    public void setAgencyOrcid(AgencyOrcid value) {
        this.agencyOrcid = value;
    }

    /**
     * Gets the value of the agencyName property.
     * 
     * @return
     *     possible object is
     *     {@link AgencyName }
     *     
     */
    public AgencyName getAgencyName() {
        return agencyName;
    }

    /**
     * Sets the value of the agencyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link AgencyName }
     *     
     */
    public void setAgencyName(AgencyName value) {
        this.agencyName = value;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (!(o instanceof FundingAgency)) {
            return false;
        }

        FundingAgency that = (FundingAgency) o;

        if (agencyName != null ? !agencyName.equals(that.agencyName) : that.agencyName != null) {
            return false;
        }
        if (agencyOrcid != null ? !agencyOrcid.equals(that.agencyOrcid) : that.agencyOrcid != null) {
            return false;
        }

        return true;
    }

    @Override
    public int hashCode() {
        int result = agencyOrcid != null ? agencyOrcid.hashCode() : 0;
        result = 31 * result + (agencyName != null ? agencyName.hashCode() : 0);
        return result;
    }
}
