//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.09 at 01:52:56 PM BST 
//

package org.orcid.jaxb.model.message;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;

/**
 * Java class for anonymous complex type.
 * 
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.orcid.org/ns/orcid}delegation-details" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType( propOrder = { "delegationDetails" })
@XmlRootElement(name = "given-permission-by")
public class GivenPermissionBy implements Serializable {

    private static final long serialVersionUID = 1L;
    @XmlElement(name = "delegation-details", required = true)
    protected List<DelegationDetails> delegationDetails;

    /**
     * Gets the value of the delegationDetails property.
     * 
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the delegationDetails property.
     * 
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDelegationDetails().add(newItem);
     * </pre>
     * 
     * 
     * Objects of the following type(s) are allowed in the list
     * {@link DelegationDetails }
     * 
     * A List of DelegationDetails objects
     * 
     * @return a List of DelegationDetails objects
     * 
     * 
     */
    public List<DelegationDetails> getDelegationDetails() {
        if (delegationDetails == null) {
            delegationDetails = new ArrayList<DelegationDetails>();
        }
        return this.delegationDetails;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (!(o instanceof GivenPermissionBy)) {
            return false;
        }

        GivenPermissionBy that = (GivenPermissionBy) o;

        if (delegationDetails != null ? !delegationDetails.equals(that.delegationDetails) : that.delegationDetails != null) {
            return false;
        }

        return true;
    }

    @Override
    public int hashCode() {
        return delegationDetails != null ? delegationDetails.hashCode() : 0;
    }
}
