//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.19 at 01:44:12 PM BST 
//

package org.orcid.jaxb.model.message;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the org.orcid.jaxb.model.message package.
 * 
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _WorkExternalIdentifierId_QNAME = new QName("http://www.orcid.org/ns/orcid", "work-external-identifier-id");
    private final static QName _CreationMethod_QNAME = new QName("http://www.orcid.org/ns/orcid", "creation-method");
    private final static QName _DisambiguatedAffiliationIdentifier_QNAME = new QName("http://www.orcid.org/ns/orcid", "disambiguated-affiliation-identifier");
    private final static QName _DisambiguationSource_QNAME = new QName("http://www.orcid.org/ns/orcid", "disambiguation-source");
    private final static QName _WorkExternalIdentifierType_QNAME = new QName("http://www.orcid.org/ns/orcid", "work-external-identifier-type");
    private final static QName _StartDate_QNAME = new QName("http://www.orcid.org/ns/orcid", "start-date");
    private final static QName _ContributorRole_QNAME = new QName("http://www.orcid.org/ns/orcid", "contributor-role");
    private final static QName _WorkType_QNAME = new QName("http://www.orcid.org/ns/orcid", "work-type");
    private final static QName _AffiliationType_QNAME = new QName("http://www.orcid.org/ns/orcid", "affiliation-type");
    private final static QName _ContributorSequence_QNAME = new QName("http://www.orcid.org/ns/orcid", "contributor-sequence");
    private final static QName _ShortDescription_QNAME = new QName("http://www.orcid.org/ns/orcid", "short-description");
    private final static QName _MessageVersion_QNAME = new QName("http://www.orcid.org/ns/orcid", "message-version");
    private final static QName _Locale_QNAME = new QName("http://www.orcid.org/ns/orcid", "locale");
    private final static QName _EndDate_QNAME = new QName("http://www.orcid.org/ns/orcid", "end-date");
    private final static QName _WorkSource_QNAME = new QName("http://www.orcid.org/ns/orcid", "work-source");
    private final static QName _WorkCitation_QNAME = new QName("http://www.orcid.org/ns/orcid", "work-citation");

    /**
     * Create a new ObjectFactory that can be used to create new instances of
     * schema derived classes for package: org.orcid.jaxb.model.message
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SourceOrcid }
     * 
     * @return a SourceOrcid object
     * 
     */
    public SourceOrcid createSourceOrcid() {
        return new SourceOrcid();
    }

    /**
     * Create an instance of {@link FundingExternalIdentifier }
     * 
     * @return a FundingExternalIdentifier object
     * 
     */
    public FundingExternalIdentifier createFundingExternalIdentifier() {
        return new FundingExternalIdentifier();
    }

    /**
     * Create an instance of {@link FundingContributors }
     * 
     * @return a FundingContributors object
     * 
     */
    public FundingContributors createFundingContributors() {
        return new FundingContributors();
    }
    
    /**
     * Create an instance of {@link GrantExternalProgram }
     * 
     * @return a GrantExternalProgram object
     * 
     */
    public GrantExternalProgram createGrantExternalProgram() {
        return new GrantExternalProgram();
    }

    /**
     * Create an instance of {@link SendChangeNotifications }
     * 
     * @return a SendChangeNotifications object
     * 
     */
    public SendChangeNotifications createSendChangeNotifications() {
        return new SendChangeNotifications();
    }

    /**
     * Create an instance of {@link ApplicationWebsite }
     * 
     * @return the ApplicationWebsite created
     * 
     */
    public ApplicationWebsite createApplicationWebsite() {
        return new ApplicationWebsite();
    }

    /**
     * Create an instance of {@link GivenPermissionTo }
     * 
     * @return a GivenPermissionTo object
     * 
     */
    public GivenPermissionTo createGivenPermissionTo() {
        return new GivenPermissionTo();
    }

    /**
     * Create an instance of {@link DelegationDetails }
     * 
     * @return a DelegationDetails object
     * 
     */
    public DelegationDetails createDelegationDetails() {
        return new DelegationDetails();
    }

    /**
     * Create an instance of {@link ApprovalDate }
     * 
     * @return an ApprovalDate object
     * 
     */
    public ApprovalDate createApprovalDate() {
        return new ApprovalDate();
    }

    /**
     * Create an instance of {@link DelegateSummary }
     * 
     * @return a DelegateSummary object
     * 
     */
    public DelegateSummary createDelegateSummary() {
        return new DelegateSummary();
    }

    /**
     * Create an instance of {@link Orcid }
     * 
     * @return an Orcid object
     * 
     */
    public Orcid createOrcid() {
        return new Orcid();
    }

    /**
     * Create an instance of {@link CreditName }
     * 
     * @return a CreditName object
     * 
     */
    public CreditName createCreditName() {
        return new CreditName();
    }

    /**
     * Create an instance of {@link AffiliationCity }
     * 
     * @return the AffiliationCity created
     * 
     */
    public AffiliationCity createCity() {
        return new AffiliationCity();
    }

    /**
     * Create an instance of {@link PublicationDate }
     * 
     * @return a PublicationDate object
     * 
     */
    public PublicationDate createPublicationDate() {
        return new PublicationDate();
    }

    /**
     * Create an instance of {@link FuzzyDate }
     * 
     * @return a FuzzyDate object
     * 
     */
    public FuzzyDate createFuzzyDate() {
        return new FuzzyDate();
    }

    /**
     * Create an instance of {@link Year }
     * 
     * @return a Year object
     * 
     */
    public Year createYear() {
        return new Year();
    }

    /**
     * Create an instance of {@link Month }
     * 
     * @return a Month object
     * 
     */
    public Month createMonth() {
        return new Month();
    }

    /**
     * Create an instance of {@link Day }
     * 
     * @return a Day object
     * 
     */
    public Day createDay() {
        return new Day();
    }

    /**
     * Create an instance of {@link Delegation }
     * 
     * @return a Delegation object
     * 
     */
    public Delegation createDelegation() {
        return new Delegation();
    }

    /**
     * Create an instance of {@link GivenPermissionBy }
     * 
     * @return a GivenPermissionBy object
     * 
     */
    public GivenPermissionBy createGivenPermissionBy() {
        return new GivenPermissionBy();
    }

    /**
     * Create an instance of {@link FundingList }
     * 
     * @return a FundingList object
     * 
     */
    public FundingList createFundingList() {
        return new FundingList();
    }

    /**
     * Create an instance of {@link Funding }
     * 
     * @return a Funding object
     * 
     */
    public Funding createFunding() {
        return new Funding();
    }

    /**
     * Create an instance of {@link FundingAgency }
     * 
     * @return a FundingAgency object
     * 
     */
    public FundingAgency createFundingAgency() {
        return new FundingAgency();
    }

    /**
     * Create an instance of {@link AgencyOrcid }
     * 
     * @return an AgencyOrcid object
     * 
     */
    public AgencyOrcid createAgencyOrcid() {
        return new AgencyOrcid();
    }

    /**
     * Create an instance of {@link AgencyName }
     * 
     * @return an AgencyName object
     * 
     */
    public AgencyName createAgencyName() {
        return new AgencyName();
    }
   
    /**
     * Create an instance of {@link GrantDate }
     * 
     * @return a GrantDate object
     * 
     */
    public GrantDate createGrantDate() {
        return new GrantDate();
    }    

    /**
     * Create an instance of {@link Contributor }
     * 
     * @return a Contributor object
     * 
     */
    public Contributor createContributor() {
        return new Contributor();
    }

    /**
     * Create an instance of {@link ContributorOrcid }
     * 
     * @return a ContributorOrcid object
     * 
     */
    public ContributorOrcid createContributorOrcid() {
        return new ContributorOrcid();
    }

    /**
     * Create an instance of {@link ContributorEmail }
     * 
     * @return a ContributorEmail object
     * 
     */
    public ContributorEmail createContributorEmail() {
        return new ContributorEmail();
    }

    /**
     * Create an instance of {@link ContributorAttributes }
     * 
     * @return a ContributorAttributes object
     * 
     */
    public ContributorAttributes createContributorAttributes() {
        return new ContributorAttributes();
    }

    /**
     * Create an instance of {@link GrantSources }
     * 
     * @return a GrantSources object
     * 
     */
    public GrantSources createGrantSources() {
        return new GrantSources();
    }

    /**
     * Create an instance of {@link Source }
     * 
     * @return a Source object
     * 
     */
    public Source createSource() {
        return new Source();
    }

    /**
     * Create an instance of {@link SourceName }
     * 
     * @return a SourceName object
     * 
     */
    public SourceName createSourceName() {
        return new SourceName();
    }

    /**
     * Create an instance of {@link SourceDate }
     * 
     * @return a SourceDate object
     * 
     */
    public SourceDate createSourceDate() {
        return new SourceDate();
    }

    /**
     * Create an instance of {@link ExternalIdCommonName }
     * 
     * @return an ExternalIdCommonName object
     * 
     */
    public ExternalIdCommonName createExternalIdCommonName() {
        return new ExternalIdCommonName();
    }

    /**
     * Create an instance of {@link OrcidHistory }
     * 
     * @return an OrcidHistory object
     * 
     */
    public OrcidHistory createOrcidHistory() {
        return new OrcidHistory();
    }

    /**
     * Create an instance of {@link CompletionDate }
     * 
     * @return a CompletionDate object
     * 
     */
    public CompletionDate createCompletionDate() {
        return new CompletionDate();
    }

    /**
     * Create an instance of {@link SubmissionDate }
     * 
     * @return a SubmissionDate object
     * 
     */
    public SubmissionDate createSubmissionDate() {
        return new SubmissionDate();
    }

    /**
     * Create an instance of {@link LastModifiedDate }
     * 
     * @return a LastModifiedDate object
     * 
     */
    public LastModifiedDate createLastModifiedDate() {
        return new LastModifiedDate();
    }

    /**
     * Create an instance of {@link Claimed }
     * 
     * @return a Claimed object
     * 
     */
    public Claimed createClaimed() {
        return new Claimed();
    }

    /**
     * Create an instance of {@link DeactivationDate }
     * 
     * @return a DeactivationDate object
     * 
     */
    public DeactivationDate createDeactivationDate() {
        return new DeactivationDate();
    }

    /**
     * Create an instance of {@link RoleTitle }
     * 
     * @return a RoleTitle object
     * 
     */
    public RoleTitle createRoleTitle() {
        return new RoleTitle();
    }

    /**
     * Create an instance of {@link ApplicationSummary }
     * 
     * @return an ApplicationSummary object
     * 
     */
    public ApplicationSummary createApplicationSummary() {
        return new ApplicationSummary();
    }

    /**
     * Create an instance of {@link ApplicationOrcid }
     * 
     * @return an ApplicationOrcid object
     * 
     */
    public ApplicationOrcid createApplicationOrcid() {
        return new ApplicationOrcid();
    }

    /**
     * Create an instance of {@link ApplicationName }
     * 
     * @return an ApplicationName object
     * 
     */
    public ApplicationName createApplicationName() {
        return new ApplicationName();
    }

    /**
     * Create an instance of {@link ScopePaths }
     * 
     * @return a ScopePaths object
     * 
     */
    public ScopePaths createScopePaths() {
        return new ScopePaths();
    }

    /**
     * Create an instance of {@link ScopePath }
     * 
     * @return a ScopePath object
     * 
     */
    public ScopePath createScopePath() {
        return new ScopePath();
    }

    /**
     * Create an instance of {@link Affiliation }
     * 
     * @return an Affiliation object
     * 
     */
    public Affiliation createAffiliation() {
        return new Affiliation();
    }

    /**
     * Create an instance of {@link AffiliationAddress }
     * 
     * @return an AffiliationAddress object
     * 
     */
    public AffiliationAddress createAffiliationAddress() {
        return new AffiliationAddress();
    }

    /**
     * Create an instance of {@link AffiliationRegion }
     * 
     * @return an AffiliationRegion object
     * 
     */
    public AffiliationRegion createRegion() {
        return new AffiliationRegion();
    }

    /**
     * Create an instance of {@link Country }
     * 
     * @return a Country object
     * 
     */
    public Country createCountry() {
        return new Country();
    }

    /**
     * Create an instance of {@link DepartmentName }
     * 
     * @return a DepartmentName object
     * 
     */
    public DepartmentName createDepartmentName() {
        return new DepartmentName();
    }

    /**
     * Create an instance of {@link WorkContributors }
     * 
     * @return a DepartmentName object
     * 
     */
    public WorkContributors createWorkContributors() {
        return new WorkContributors();
    }

    /**
     * Create an instance of {@link ExternalIdentifier }
     * 
     * @return an ExternalIdenfitier object
     * 
     */
    public ExternalIdentifier createExternalIdentifier() {
        return new ExternalIdentifier();
    }

    /**
     * Create an instance of {@link ExternalIdSource }
     * 
     * @return an ExtrenalIdSource object
     * 
     */
    public ExternalIdSource createExternalIdOrcid() {
        return new ExternalIdSource();
    }

    /**
     * Create an instance of {@link ExternalIdReference }
     * 
     * @return an ExternalIdReference object
     * 
     */
    public ExternalIdReference createExternalIdReference() {
        return new ExternalIdReference();
    }

    /**
     * Create an instance of {@link ExternalIdUrl }
     * 
     * @return an ExternalIdUrl object
     * 
     */
    public ExternalIdUrl createExternalIdUrl() {
        return new ExternalIdUrl();
    }

    /**
     * Create an instance of {@link Affiliations }
     * 
     * @return an Affiliations object
     * 
     */
    public Affiliations createAffiliations() {
        return new Affiliations();
    }

    /**
     * Create an instance of {@link Assignee }
     * 
     * @return an Assignee object
     * 
     */
    public Assignee createAssignee() {
        return new Assignee();
    }

    /**
     * Create an instance of {@link AssigneeOrcid }
     * 
     * @return an AssigneeOrcid object
     * 
     */
    public AssigneeOrcid createAssigneeOrcid() {
        return new AssigneeOrcid();
    }

    /**
     * Create an instance of {@link AssigneeName }
     * 
     * @return an AssigneeName object
     * 
     */
    public AssigneeName createAssigneeName() {
        return new AssigneeName();
    }


    /**
     * Create an instance of {@link OrcidPreferences }
     * 
     * @return an OrcidPreferences object
     * 
     */
    public OrcidPreferences createOrcidPreferences() {
        return new OrcidPreferences();
    }

    /**
     * Create an instance of {@link OrcidActivities }
     * 
     * @return an OrcidActivities object
     * 
     */
    public OrcidActivities createOrcidActivities() {
        return new OrcidActivities();
    }

    /**
     * Create an instance of {@link OrcidWorks }
     * 
     * @return an OrcidWorks object
     * 
     */
    public OrcidWorks createOrcidWorks() {
        return new OrcidWorks();
    }

    /**
     * Create an instance of {@link OrcidWork }
     * 
     * @return an OrcidWork object
     * 
     */
    public OrcidWork createOrcidWork() {
        return new OrcidWork();
    }

    /**
     * Create an instance of {@link WorkTitle }
     * 
     * @return a WorkTitle object
     * 
     */
    public WorkTitle createWorkTitle() {
        return new WorkTitle();
    }

    /**
     * Create an instance of {@link Title }
     * 
     * @return a Title object
     * 
     */
    public Title createTitle() {
        return new Title();
    }

    /**
     * Create an instance of {@link Subtitle }
     * 
     * @return a Subtitle object
     * 
     */
    public Subtitle createSubtitle() {
        return new Subtitle();
    }

    /**
     * Create an instance of {@link Citation }
     * 
     * @return a Citation object
     * 
     */
    public Citation createCitation() {
        return new Citation();
    }

    /**
     * Create an instance of {@link WorkExternalIdentifiers }
     * 
     * @return a WorkExternalIdentifiers object
     * 
     */
    public WorkExternalIdentifiers createWorkExternalIdentifiers() {
        return new WorkExternalIdentifiers();
    }

    /**
     * Create an instance of {@link WorkExternalIdentifier }
     * 
     * @return a WorkExternalIdentifier object
     * 
     */
    public WorkExternalIdentifier createWorkExternalIdentifier() {
        return new WorkExternalIdentifier();
    }

    /**
     * Create an instance of {@link Url }
     * 
     * @return a Url object
     * 
     */
    public Url createUrl() {
        return new Url();
    }

    /**
     * Create an instance of {@link SecurityDetails }
     * 
     * @return a SecurityDetails object
     * 
     */
    public SecurityDetails createSecurityDetails() {
        return new SecurityDetails();
    }

    /**
     * Create an instance of {@link EncryptedPassword }
     * 
     * @return an EncryptedPassword object
     * 
     */
    public EncryptedPassword createEncryptedPassword() {
        return new EncryptedPassword();
    }

    /**
     * Create an instance of {@link FamilyName }
     * 
     * @return a FamilyName object
     * 
     */
    public FamilyName createFamilyName() {
        return new FamilyName();
    }

    /**
     * Create an instance of {@link OtherNames }
     * 
     * @return an OtherNames object
     * 
     */
    public OtherNames createOtherNames() {
        return new OtherNames();
    }

    /**
     * Create an instance of {@link OtherName }
     * 
     * @return an OtherName object
     * 
     */
    public OtherName createOtherName() {
        return new OtherName();
    }

    /**
     * Create an instance of {@link Preferences }
     * 
     * @return a Preferences object
     * 
     */
    public Preferences createPreferences() {
        return new Preferences();
    }

    /**
     * Create an instance of {@link SendOrcidNews }
     * 
     * @return a SendOrcidNews object
     * 
     */
    public SendOrcidNews createSendOrcidNews() {
        return new SendOrcidNews();
    }

    /**
     * Create an instance of {@link WorkVisibilityDefault }
     * 
     * @return a WorkVisibilityDefault object
     * 
     */
    public WorkVisibilityDefault createWorkVisibilityDefault() {
        return new WorkVisibilityDefault();
    }

    /**
     * Create an instance of {@link OrcidBio }
     * 
     * @return an OrcidBio object
     * 
     */
    public OrcidBio createOrcidBio() {
        return new OrcidBio();
    }

    /**
     * Create an instance of {@link PersonalDetails }
     * 
     * @return a PersonalDetails object
     * 
     */
    public PersonalDetails createPersonalDetails() {
        return new PersonalDetails();
    }

    /**
     * Create an instance of {@link GivenNames }
     * 
     * @return a GivenNames object
     * 
     */
    public GivenNames createGivenNames() {
        return new GivenNames();
    }

    /**
     * Create an instance of {@link Biography }
     * 
     * @return a Biography object
     * 
     */
    public Biography createBiography() {
        return new Biography();
    }

    /**
     * Create an instance of {@link ResearcherUrls }
     * 
     * @return a ResearcherUrls object
     * 
     */
    public ResearcherUrls createResearcherUrls() {
        return new ResearcherUrls();
    }

    /**
     * Create an instance of {@link ResearcherUrl }
     * 
     * @return a ResearcherUrl object
     * 
     */
    public ResearcherUrl createResearcherUrl() {
        return new ResearcherUrl();
    }

    /**
     * Create an instance of {@link UrlName }
     *
     * @return a UrlName object	
     * 
     */
    public UrlName createUrlName() {
        return new UrlName();
    }

    /**
     * Create an instance of {@link ContactDetails }
     * 
     * @return a ContactDetails object
     * 
     */
    public ContactDetails createContactDetails() {
        return new ContactDetails();
    }

    /**
     * Create an instance of {@link Email }
     * 
     * @return an Email object
     * 
     */
    public Email createEmail() {
        return new Email();
    }

    /**
     * Create an instance of {@link Address }
     * 
     * @return an Address object
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link Keywords }
     * 
     * @return a Keywords object
     * 
     */
    public Keywords createKeywords() {
        return new Keywords();
    }

    /**
     * Create an instance of {@link Keyword }
     * 
     * @return a Keyword object
     * 
     */
    public Keyword createKeyword() {
        return new Keyword();
    }

    /**
     * Create an instance of {@link ExternalIdentifiers }
     * 
     * @return an ExternalIdentifiers object
     * 
     */
    public ExternalIdentifiers createExternalIdentifiers() {
        return new ExternalIdentifiers();
    }

    /**
     * Create an instance of {@link Applications }
     * 
     * @return an Applications object
     * 
     */
    public Applications createApplications() {
        return new Applications();
    }

    /**
     * Create an instance of {@link OrcidSearchResult }
     * 
     * @return an OrcidSearchResult object
     * 
     */
    public OrcidSearchResult createOrcidSearchResult() {
        return new OrcidSearchResult();
    }

    /**
     * Create an instance of {@link RelevancyScore }
     * 
     * @return a RelevancyScore object
     * 
     */
    public RelevancyScore createRelevancyScore() {
        return new RelevancyScore();
    }

    /**
     * Create an instance of {@link OrcidProfile }
     * 
     * @return an OrcidProfile object
     * 
     */
    public OrcidProfile createOrcidProfile() {
        return new OrcidProfile();
    }

    /**
     * Create an instance of {@link OrcidInternal }
     * 
     * @return an OrcidInternal object
     * 
     */
    public OrcidInternal createOrcidInternal() {
        return new OrcidInternal();
    }

    /**
     * Create an instance of {@link ErrorDesc }
     * 
     * @return an ErrorDesc object
     * 
     */
    public ErrorDesc createErrorDesc() {
        return new ErrorDesc();
    }

    /**
     * Create an instance of {@link OrcidMessage }
     * 
     * @return an OrcidMessage object
     * 
     */
    public OrcidMessage createOrcidMessage() {
        return new OrcidMessage();
    }

    /**
     * Create an instance of {@link OrcidSearchResults }
     * 
     * @return an OrcidSearchResults object
     * 
     */
    public OrcidSearchResults createOrcidSearchResults() {
        return new OrcidSearchResults();
    }

    /**
     * Create an instance of {@link SourceReference }
     * 
     * @return a SourceReference object
     * 
     */
    public SourceReference createSourceReference() {
        return new SourceReference();
    }

    /**
     * Create a JAXBElement representation of the given value
     * 
     * @param value - a work external identifier
     * @return a JAXBElement object
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/orcid", name = "work-external-identifier-id")
    public JAXBElement<String> createWorkExternalIdentifierId(String value) {
        return new JAXBElement<String>(_WorkExternalIdentifierId_QNAME, String.class, null, value);
    }

    /**
     * Create a JAXBElement representation of the given CreationMethod object
     * 
     * @param value - a CreationMethod object
     * @return a JAXBElement representation of the given CreationMethod object
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/orcid", name = "creation-method")
    public JAXBElement<CreationMethod> createCreationMethod(CreationMethod value) {
        return new JAXBElement<CreationMethod>(_CreationMethod_QNAME, CreationMethod.class, null, value);
    }

    /**
     * Create a JAXBElement representation of the given disambiguated affiliation idenfitier value
     * 
     * @param value - a disambiguatedAffiliationIdentifier 
     * @return a JAXBElement object
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/orcid", name = "disambiguated-affiliation-identifier")
    public JAXBElement<String> createDisambiguatedAffiliationIdentifier(String value) {
        return new JAXBElement<String>(_DisambiguatedAffiliationIdentifier_QNAME, String.class, null, value);
    }

    /**
     * Create a JAXBElement representation of the given value
     * 
     * @param value - a disambiguation source
     * @return a JAXBElement object
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/orcid", name = "disambiguation-source")
    public JAXBElement<String> createDisambiguationSource(String value) {
        return new JAXBElement<String>(_DisambiguationSource_QNAME, String.class, null, value);
    }

    /**
     * Create a JAXBElement representation of the given value
     * 
     * @param value - a work external identifier
     * @return a JAXBElement object
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/orcid", name = "work-external-identifier-type")
    public JAXBElement<String> createWorkExternalIdentifierType(String value) {
        return new JAXBElement<String>(_WorkExternalIdentifierType_QNAME, String.class, null, value);
    }

    /**
     * Create a JAXBElement representation of the given FuzzyDate value
     * 
     * @param value - a FuzzyDate
     * @return a JAXBElement object
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/orcid", name = "start-date")
    public JAXBElement<FuzzyDate> createStartDate(FuzzyDate value) {
        return new JAXBElement<FuzzyDate>(_StartDate_QNAME, FuzzyDate.class, null, value);
    }

    /**
     * Create a JAXBElement representation of the given contributor role value
     * 
     * @param value - a contributor role
     * @return a JAXBElement object
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/orcid", name = "contributor-role")
    public JAXBElement<String> createContributorRole(String value) {
        return new JAXBElement<String>(_ContributorRole_QNAME, String.class, null, value);
    }

    /**
     * Create a JAXBElement representation of the given work type value
     * 
     * @param value - a work type
     * @return a JAXBElement object
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/orcid", name = "work-type")
    public JAXBElement<String> createWorkType(String value) {
        return new JAXBElement<String>(_WorkType_QNAME, String.class, null, value);
    }

    /**
     * Create a JAXBElement representation of the given affiliation type value
     * 
     * @param value - an affiliation type
     * @return a JAXBElement object
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/orcid", name = "affiliation-type")
    public JAXBElement<String> createAffiliationType(String value) {
        return new JAXBElement<String>(_AffiliationType_QNAME, String.class, null, value);
    }

    /**
     * Create a JAXBElement representation of the given contributor sequence value
     * 
     * @param value - a contributor sequence
     * @return a JAXBElement object
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/orcid", name = "contributor-sequence")
    public JAXBElement<String> createContributorSequence(String value) {
        return new JAXBElement<String>(_ContributorSequence_QNAME, String.class, null, value);
    }

    /**
     * Create a JAXBElement representation of the given short description value
     * 
     * @param value - a short description
     * @return a JAXBElement object
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/orcid", name = "short-description")
    public JAXBElement<String> createShortDescription(String value) {
        return new JAXBElement<String>(_ShortDescription_QNAME, String.class, null, value);
    }

    /**
     * Create a JAXBElement representation of the given message version value
     * 
     * @param value - a message version
     * @return a JAXBElement object
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/orcid", name = "message-version")
    public JAXBElement<String> createMessageVersion(String value) {
        return new JAXBElement<String>(_MessageVersion_QNAME, String.class, null, value);
    }

    /**
     * Create a JAXBElement representation of the given locale string value
     * 
     * @param value - a locale string
     * @return a JAXBElement object
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/orcid", name = "locale")
    public JAXBElement<String> createLocale(String value) {
        return new JAXBElement<String>(_Locale_QNAME, String.class, null, value);
    }

    /**
     * Create a JAXBElement representation of the given FuzzyDate value
     * 
     * @param value - a FuzzyDate
     * @return a JAXBElement object
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/orcid", name = "end-date")
    public JAXBElement<FuzzyDate> createEndDate(FuzzyDate value) {
        return new JAXBElement<FuzzyDate>(_EndDate_QNAME, FuzzyDate.class, null, value);
    }

    /**
     * Create a JAXBElement representation of the given work source value
     * 
     * @param value - a work source
     * @return a JAXBElement object
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/orcid", name = "work-source")
    public JAXBElement<Object> createWorkSource(Object value) {
        return new JAXBElement<Object>(_WorkSource_QNAME, Object.class, null, value);
    }

    /**
     * Create a JAXBElement representation of the given Citation value
     * 
     * @param value - a Citation
     * @return a JAXBElement object
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/orcid", name = "work-citation")
    public JAXBElement<Citation> createWorkCitation(Citation value) {
        return new JAXBElement<Citation>(_WorkCitation_QNAME, Citation.class, null, value);
    }

}
