//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.15 at 12:09:14 PM GMT 
//

package org.orcid.jaxb.model.message;

import java.io.Serializable;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlTransient;
import jakarta.xml.bind.annotation.XmlType;

/**
 * Java class for anonymous complex type.
 * 
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.orcid.org/ns/orcid}send-email-frequency-days"/&gt;
 *         &lt;element ref="{http://www.orcid.org/ns/orcid}send-change-notifications"/&gt;
 *         &lt;element ref="{http://www.orcid.org/ns/orcid}send-orcid-news"/&gt;
 *         &lt;element ref="{http://www.orcid.org/ns/orcid}send-member-update-requests"/&gt;
 *         &lt;element ref="{http://www.orcid.org/ns/orcid}activities-visibility-default"/&gt;
 *         &lt;element ref="{http://www.orcid.org/ns/orcid}developer-tools-enabled" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "sendEmailFrequencyDays", "sendChangeNotifications", "sendAdministrativeChangeNotifications", "sendOrcidNews", "sendMemberUpdateRequests", "activitiesVisibilityDefault",
        "workVisibilityDefault", "developerToolsEnabled" })
@XmlRootElement(name = "preferences")
public class Preferences implements Serializable {

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "send-email-frequency-days")
    protected String sendEmailFrequencyDays;
    @XmlElement(name = "send-change-notifications", required = true)
    protected SendChangeNotifications sendChangeNotifications;
    @XmlElement(name = "send-administrative-change-notifications", required = true)
    protected SendAdministrativeChangeNotifications sendAdministrativeChangeNotifications;
    @XmlElement(name = "send-orcid-news", required = true)
    protected SendOrcidNews sendOrcidNews;
    @XmlElement(name = "send-member-update-requests", required = true)
    protected Boolean sendMemberUpdateRequests;
    // as of 1.2_rc4 WorkVisibilityDefault is replaced by
    // ActivitiesVisibilityDefault
    @XmlElement(name = "work-visibility-default")
    protected WorkVisibilityDefault workVisibilityDefault;
    @XmlElement(name = "activities-visibility-default")
    private ActivitiesVisibilityDefault activitiesVisibilityDefault;
    @XmlElement(name = "developer-tools-enabled")
    private DeveloperToolsEnabled developerToolsEnabled;
    @XmlTransient
    private Boolean notificationsEnabled;

    /**
     * Gets the value of the sendEmailFrequencyDays property.
     * 
     * @return sendEmailFrequencyDays string
     * 
     */
    public String getSendEmailFrequencyDays() {
        return sendEmailFrequencyDays;
    }

    /**
     * Sets the value of the sendEmailFrequencyDays property.
     * 
     * @param value - sendEmailFrequencyDays string
     * 
     */
    public void setSendEmailFrequencyDays(String value) {
        this.sendEmailFrequencyDays = value;
    }

    /**
     * Gets the value of the sendChangeNotifications property.
     * 
     * @return possible object is {@link SendChangeNotifications }
     * 
     */
    public SendChangeNotifications getSendChangeNotifications() {
        return sendChangeNotifications;
    }

    /**
     * Sets the value of the sendChangeNotifications property.
     * 
     * @param value
     *            allowed object is {@link SendChangeNotifications }
     * 
     */
    public void setSendChangeNotifications(SendChangeNotifications value) {
        this.sendChangeNotifications = value;
    }
    
    public SendAdministrativeChangeNotifications getSendAdministrativeChangeNotifications() {
        return sendAdministrativeChangeNotifications;
    }

    public void setSendAdministrativeChangeNotifications(SendAdministrativeChangeNotifications sendAdministrativeChangeNotifications) {
        this.sendAdministrativeChangeNotifications = sendAdministrativeChangeNotifications;
    }

    /**
     * Gets the value of the sendOrcidNews property.
     * 
     * @return possible object is {@link SendOrcidNews }
     * 
     */
    public SendOrcidNews getSendOrcidNews() {
        return sendOrcidNews;
    }

    /**
     * Sets the value of the sendOrcidNews property.
     * 
     * @param value
     *            allowed object is {@link SendOrcidNews }
     * 
     */
    public void setSendOrcidNews(SendOrcidNews value) {
        this.sendOrcidNews = value;
    }

    public Boolean getSendMemberUpdateRequests() {
        return sendMemberUpdateRequests;
    }

    public void setSendMemberUpdateRequests(Boolean sendMemberUpdateRequests) {
        this.sendMemberUpdateRequests = sendMemberUpdateRequests;
    }

    /**
     * Gets the value of the workVisibilityDefault property.
     * 
     * @return the WorkVisibilityDefault
     * 
     * @deprecated 
     * 
     */
    public WorkVisibilityDefault getWorkVisibilityDefault() {
        return workVisibilityDefault;
    }

    /**
     * Sets the value of the workVisibilityDefault property.
     * 
     * @param value - the WorkVisibilityDefault
     * 
     * @deprecated
     * 
     */
    public void setWorkVisibilityDefault(WorkVisibilityDefault value) {
        this.workVisibilityDefault = value;
    }

    public ActivitiesVisibilityDefault getActivitiesVisibilityDefault() {
        return activitiesVisibilityDefault;
    }

    public void setActivitiesVisibilityDefault(ActivitiesVisibilityDefault activitiesVisibilityDefault) {
        this.activitiesVisibilityDefault = activitiesVisibilityDefault;
    }

    public DeveloperToolsEnabled getDeveloperToolsEnabled() {
        return developerToolsEnabled;
    }

    public void setDeveloperToolsEnabled(DeveloperToolsEnabled developerToolsEnabled) {
        this.developerToolsEnabled = developerToolsEnabled;
    }

    public Boolean getNotificationsEnabled() {
        return notificationsEnabled;
    }

    public void setNotificationsEnabled(Boolean notificationsEnabled) {
        this.notificationsEnabled = notificationsEnabled;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((sendChangeNotifications == null) ? 0 : sendChangeNotifications.hashCode());
        result = prime * result + ((sendOrcidNews == null) ? 0 : sendOrcidNews.hashCode());
        result = prime * result + ((workVisibilityDefault == null) ? 0 : workVisibilityDefault.hashCode());
        result = prime * result + ((activitiesVisibilityDefault == null) ? 0 : activitiesVisibilityDefault.hashCode());
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        Preferences other = (Preferences) obj;
        if (sendChangeNotifications == null) {
            if (other.sendChangeNotifications != null)
                return false;
        } else if (!sendChangeNotifications.equals(other.sendChangeNotifications))
            return false;
        if (sendOrcidNews == null) {
            if (other.sendOrcidNews != null)
                return false;
        } else if (!sendOrcidNews.equals(other.sendOrcidNews))
            return false;
        if (workVisibilityDefault == null) {
            if (other.workVisibilityDefault != null)
                return false;
        } else if (!workVisibilityDefault.equals(other.workVisibilityDefault))
            return false;
        if (activitiesVisibilityDefault == null) {
            if (other.activitiesVisibilityDefault != null)
                return false;
        } else if (!activitiesVisibilityDefault.equals(other.activitiesVisibilityDefault))
            return false;
        return true;
    }

}
