//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.09 at 01:52:56 PM BST 
//

package org.orcid.jaxb.model.message;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;

/**
 * Java class for anonymous complex type.
 * 
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.orcid.org/ns/orcid}researcher-url" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attGroup ref="{http://www.orcid.org/ns/orcid}visibility"/&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType( propOrder = { "researcherUrl" })
@XmlRootElement(name = "researcher-urls")
public class ResearcherUrls implements Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;

    @XmlElement(name = "researcher-url")
    private List<ResearcherUrl> researcherUrl;

    @XmlAttribute
    protected Visibility visibility;

    public Visibility getVisibility() {
        return visibility;
    }

    public void setVisibility(Visibility visibility) {
        this.visibility = visibility;
    }

    /**
     * Gets the value of the researcherUrl property.
     *
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the researcherUrl property.
     * 
     * For example, to add a new item, do as follows:
     * <pre>
     *    getResearcherUrl().add(newItem);
     * </pre>
     * 
     * Objects of the following type(s) are allowed in the list
     * {@link ResearcherUrl }
     * 
     * @return a List of ResearcherUrl objects
     * 
     */
    public List<ResearcherUrl> getResearcherUrl() {
        if (researcherUrl == null) {
            researcherUrl = new ArrayList<ResearcherUrl>();
        }
        return this.researcherUrl;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (!(o instanceof ResearcherUrls)) {
            return false;
        }

        ResearcherUrls that = (ResearcherUrls) o;

        if (getResearcherUrl() != null ? !getResearcherUrl().equals(that.getResearcherUrl()) : that.getResearcherUrl() != null) {
            return false;
        }
        if (visibility != that.visibility) {
            return false;
        }

        return true;
    }

    @Override
    public int hashCode() {
        int result = getResearcherUrl() != null ? getResearcherUrl().hashCode() : 0;
        result = 31 * result + (visibility != null ? visibility.hashCode() : 0);
        return result;
    }

    public void setResearcherUrl(List<ResearcherUrl> researcherUrl) {
        this.researcherUrl = researcherUrl;
    }
}
