//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.22 at 06:46:00 PM BST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://www.orcid.org/ns/activities", xmlns = {
        @jakarta.xml.bind.annotation.XmlNs(prefix = "activities", namespaceURI = "http://www.orcid.org/ns/activities"),
        @jakarta.xml.bind.annotation.XmlNs(prefix = "employment", namespaceURI = "http://www.orcid.org/ns/employment"),         
        @jakarta.xml.bind.annotation.XmlNs(prefix = "education", namespaceURI = "http://www.orcid.org/ns/education"),
        @jakarta.xml.bind.annotation.XmlNs(prefix = "funding", namespaceURI = "http://www.orcid.org/ns/funding"),
        @jakarta.xml.bind.annotation.XmlNs(prefix = "peer-review", namespaceURI = "http://www.orcid.org/ns/peer-review"),
        @jakarta.xml.bind.annotation.XmlNs(prefix = "work", namespaceURI = "http://www.orcid.org/ns/work"),
        @jakarta.xml.bind.annotation.XmlNs(prefix = "common", namespaceURI = "http://www.orcid.org/ns/common")}, 
        elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.orcid.jaxb.model.record.summary_v2;

