//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.09 at 01:52:56 PM BST 
//

package org.orcid.jaxb.model.common_v2;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;

import com.fasterxml.jackson.annotation.JsonValue;

import io.swagger.v3.oas.annotations.media.Schema;

import java.io.Serializable;

/**
 * Java class for orcid-type.
 * 
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;simpleType name="orcid-type"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="admin"/&gt;
 *     &lt;enumeration value="user"/&gt;
 *     &lt;enumeration value="group"/&gt;
 *     &lt;enumeration value="client"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "orcid-type")
@XmlEnum
@Schema(description = "OrcidTypeV2_0")
public enum OrcidType implements Serializable {
    @XmlEnumValue("admin")
    ADMIN("admin"), 
    @XmlEnumValue("user")
    USER("user"),   
    @XmlEnumValue("client")
    @Deprecated
    CLIENT("client"),
    @XmlEnumValue("group")
    GROUP("group");
    private final String value;

    OrcidType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }
    
    @JsonValue
    public String jsonValue() {
        return this.name();
    }
    
    public static OrcidType fromValue(String v) {
        for (OrcidType c : OrcidType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
