//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.22 at 06:46:00 PM BST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://www.orcid.org/ns/record", xmlns = {
        @jakarta.xml.bind.annotation.XmlNs(prefix = "activities", namespaceURI = "http://www.orcid.org/ns/activities"),        
        @jakarta.xml.bind.annotation.XmlNs(prefix = "address", namespaceURI = "http://www.orcid.org/ns/address"),
        @jakarta.xml.bind.annotation.XmlNs(prefix = "bulk", namespaceURI = "http://www.orcid.org/ns/bulk"),
        @jakarta.xml.bind.annotation.XmlNs(prefix = "common", namespaceURI = "http://www.orcid.org/ns/common"),        
        @jakarta.xml.bind.annotation.XmlNs(prefix = "deprecated", namespaceURI = "http://www.orcid.org/ns/deprecated"),
        @jakarta.xml.bind.annotation.XmlNs(prefix = "education", namespaceURI = "http://www.orcid.org/ns/education"),
        @jakarta.xml.bind.annotation.XmlNs(prefix = "email", namespaceURI = "http://www.orcid.org/ns/email"),
        @jakarta.xml.bind.annotation.XmlNs(prefix = "employment", namespaceURI = "http://www.orcid.org/ns/employment"),
        @jakarta.xml.bind.annotation.XmlNs(prefix = "error", namespaceURI = "http://www.orcid.org/ns/error"),
        @jakarta.xml.bind.annotation.XmlNs(prefix = "external-identifier", namespaceURI = "http://www.orcid.org/ns/external-identifier"),
        @jakarta.xml.bind.annotation.XmlNs(prefix = "funding", namespaceURI = "http://www.orcid.org/ns/funding"),
        @jakarta.xml.bind.annotation.XmlNs(prefix = "history", namespaceURI = "http://www.orcid.org/ns/history"),
        @jakarta.xml.bind.annotation.XmlNs(prefix = "internal", namespaceURI = "http://www.orcid.org/ns/internal"),
        @jakarta.xml.bind.annotation.XmlNs(prefix = "keyword", namespaceURI = "http://www.orcid.org/ns/keyword"),
        @jakarta.xml.bind.annotation.XmlNs(prefix = "other-name", namespaceURI = "http://www.orcid.org/ns/other-name"),
        @jakarta.xml.bind.annotation.XmlNs(prefix = "peer-review", namespaceURI = "http://www.orcid.org/ns/peer-review"),
        @jakarta.xml.bind.annotation.XmlNs(prefix = "person", namespaceURI = "http://www.orcid.org/ns/person"),
        @jakarta.xml.bind.annotation.XmlNs(prefix = "personal-details", namespaceURI = "http://www.orcid.org/ns/personal-details"), 
        @jakarta.xml.bind.annotation.XmlNs(prefix = "preferences", namespaceURI = "http://www.orcid.org/ns/preferences"),
        @jakarta.xml.bind.annotation.XmlNs(prefix = "record", namespaceURI = "http://www.orcid.org/ns/record"),
        @jakarta.xml.bind.annotation.XmlNs(prefix = "researcher-url", namespaceURI = "http://www.orcid.org/ns/researcher-url"),
        @jakarta.xml.bind.annotation.XmlNs(prefix = "work", namespaceURI = "http://www.orcid.org/ns/work")}, 
        elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.orcid.jaxb.model.record_v2;

