//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.22 at 06:46:00 PM BST 
//

package org.orcid.jaxb.model.v3.release.notification.custom;

import java.io.Serializable;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlTransient;
import jakarta.xml.bind.annotation.XmlType;

import org.orcid.jaxb.model.v3.release.notification.Notification;
import org.orcid.jaxb.model.v3.release.notification.NotificationType;

/**
 * Java class for anonymous complex type.
 * 
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.orcid.org/ns/common}put-code" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.orcid.org/ns/notification}notification-type"/&gt;
 *         &lt;element name="subject" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="body-text" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="body-html" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="created-date" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="sent-date" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="read-date" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="archived-date" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.orcid.org/ns/common}source" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "putCode", "notificationType", "subject", "bodyText", "bodyHtml", "createdDate", "sentDate", "readDate", "archivedDate", "source" })
@XmlRootElement(name = "notification", namespace = "http://www.orcid.org/ns/notification")
public class NotificationCustom extends Notification implements Serializable {

    private final static long serialVersionUID = 1L;
    @XmlElement(required = true)
    protected String subject;
    @XmlElement(name = "body-text", required = true)
    protected String bodyText;
    @XmlElement(name = "body-html", required = true)
    protected String bodyHtml;
    @XmlAttribute(name = "lang", namespace = "http://www.w3.org/XML/1998/namespace")
    protected String lang;
    @XmlTransient
    protected String overwrittenSourceName;

    {
        notificationType = NotificationType.CUSTOM;
    }

    /**
     * Gets the value of the subject property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getSubject() {
        return subject;
    }

    /**
     * Sets the value of the subject property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setSubject(String value) {
        this.subject = value;
    }

    /**
     * Gets the value of the bodyText property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getBodyText() {
        return bodyText;
    }

    /**
     * Sets the value of the bodyText property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setBodyText(String value) {
        this.bodyText = value;
    }

    /**
     * Gets the value of the bodyHtml property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getBodyHtml() {
        return bodyHtml;
    }

    /**
     * Sets the value of the bodyHtml property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setBodyHtml(String value) {
        this.bodyHtml = value;
    }

    public String getLang() {
        return lang;
    }

    public void setLang(String lang) {
        this.lang = lang;
    }

    /**
     * Gets the value of the overwrittenSourceName property.
     * 
     * @return possible object is {@link String }
     * 
     */
	public String getOverwrittenSourceName() {
		return overwrittenSourceName;
	}
	
	/**
     * Sets the value of the overwrittenSourceName property.
     * 
     * @param overwrittenSourceName
     *            allowed object is {@link String }
     * 
     */
	public void setOverwrittenSourceName(String overwrittenSourceName) {
		this.overwrittenSourceName = overwrittenSourceName;
	}       
}
